from __future__ import annotations

from evg.models.specs import ModelSource, ModelSpec, ModelVariant
from evg.types import RuntimeKind, SupportStatus, TaskType


BUILTIN_MODEL_SPECS: tuple[ModelSpec, ...] = (
    ModelSpec(
        id="minimax-h3",
        aliases=("minimax", "h3", "minimaxh3"),
        name="MiniMax-H3",
        organization="MiniMaxAI",
        adapter="minimax-h3",
        runtime=RuntimeKind.HYBRID,
        status=SupportStatus.SUPPORTED,
        default_variant="fl2va-pruned-fp8",
        description=(
            "EVG's current executable model mainline with adaptive 2-D DraftMap "
            "routing and native SM89 FP8/FP16 mixed attention."
        ),
        sources=(
            ModelSource("model", "https://huggingface.co/MiniMaxAI/MiniMax-H3"),
            ModelSource("checkpoint", "https://huggingface.co/Comfy-Org/MiniMax-H3"),
        ),
        variants=(
            ModelVariant(
                id="fl2va-pruned-fp8",
                name="MiniMax-H3 FL2VA pruned FP8",
                hf_repo_id="Comfy-Org/MiniMax-H3",
                tasks=(TaskType.TEXT_TO_VIDEO_WITH_SOUND,),
                resolutions=("480p", "768p"),
                fps=(24,),
                default_resolution="1344x768",
                default_fps=24,
                notes=(
                    "The released demo uses bundled official prompt conditioning.",
                    "The native MPA candidate requires SM89; dense and official Sol are controls.",
                ),
            ),
        ),
    ),
    ModelSpec(
        id="wan2.2",
        aliases=("wan", "wan2", "wan22"),
        name="Wan2.2",
        organization="Wan-AI / Wan-Video",
        adapter="wan2.2",
        runtime=RuntimeKind.DIFFUSERS,
        status=SupportStatus.ADAPTER_SCAFFOLDED,
        default_variant="t2v-a14b",
        description="Open large-scale video generation family with MoE video diffusion models.",
        sources=(
            ModelSource("code", "https://github.com/Wan-Video/Wan2.2"),
            ModelSource("model", "https://huggingface.co/Wan-AI/Wan2.2-T2V-A14B-Diffusers"),
        ),
        variants=(
            ModelVariant(
                id="t2v-a14b",
                name="Wan2.2 T2V A14B",
                hf_repo_id="Wan-AI/Wan2.2-T2V-A14B-Diffusers",
                parameter_count="27B total, 14B active",
                active_parameter_count="14B",
                tasks=(TaskType.TEXT_TO_VIDEO,),
                resolutions=("480p", "720p"),
                notes=("Two-expert MoE denoising schedule.",),
            ),
            ModelVariant(
                id="i2v-a14b",
                name="Wan2.2 I2V A14B",
                hf_repo_id="Wan-AI/Wan2.2-I2V-A14B-Diffusers",
                parameter_count="27B total, 14B active",
                active_parameter_count="14B",
                tasks=(TaskType.IMAGE_TO_VIDEO,),
                resolutions=("480p", "720p"),
            ),
            ModelVariant(
                id="ti2v-5b",
                name="Wan2.2 TI2V 5B",
                hf_repo_id="Wan-AI/Wan2.2-TI2V-5B-Diffusers",
                parameter_count="5B",
                tasks=(TaskType.TEXT_TO_VIDEO, TaskType.IMAGE_TO_VIDEO, TaskType.TEXT_IMAGE_TO_VIDEO),
                resolutions=("720p",),
                fps=(24,),
                default_fps=24,
                notes=("High-compression VAE path for text/image conditioned video.",),
            ),
            ModelVariant(
                id="s2v-14b",
                name="Wan2.2 S2V 14B",
                hf_repo_id="Wan-AI/Wan2.2-S2V-14B",
                parameter_count="14B",
                tasks=(TaskType.SPEECH_TO_VIDEO, TaskType.AUDIO_TO_VIDEO),
                resolutions=("480p", "720p"),
            ),
            ModelVariant(
                id="animate-14b",
                name="Wan2.2 Animate 14B",
                hf_repo_id="Wan-AI/Wan2.2-Animate-14B",
                parameter_count="14B",
                tasks=(TaskType.IMAGE_TO_VIDEO, TaskType.REFERENCE_TO_VIDEO),
            ),
        ),
    ),
    ModelSpec(
        id="lingbot-video",
        aliases=("lingbot", "lingbotvideo"),
        name="LingBot-Video",
        organization="Robbyant",
        adapter="lingbot-video",
        runtime=RuntimeKind.DIFFUSERS,
        status=SupportStatus.ADAPTER_SCAFFOLDED,
        default_variant="dense-1.3b",
        license_id="apache-2.0",
        description="Embodied-intelligence video generation family with dense and MoE variants.",
        sources=(
            ModelSource("code", "https://github.com/robbyant/lingbot-video"),
            ModelSource("model", "https://huggingface.co/robbyant/lingbot-video-dense-1.3b"),
            ModelSource("model", "https://huggingface.co/robbyant/lingbot-video-moe-30b-a3b"),
        ),
        variants=(
            ModelVariant(
                id="dense-1.3b",
                name="LingBot-Video Dense 1.3B",
                hf_repo_id="robbyant/lingbot-video-dense-1.3b",
                parameter_count="1.3B",
                tasks=(TaskType.TEXT_TO_IMAGE, TaskType.TEXT_TO_VIDEO, TaskType.TEXT_IMAGE_TO_VIDEO),
            ),
            ModelVariant(
                id="moe-30b-a3b",
                name="LingBot-Video MoE 30B-A3B",
                hf_repo_id="robbyant/lingbot-video-moe-30b-a3b",
                parameter_count="30B",
                active_parameter_count="3B",
                tasks=(
                    TaskType.TEXT_TO_IMAGE,
                    TaskType.TEXT_TO_VIDEO,
                    TaskType.TEXT_IMAGE_TO_VIDEO,
                    TaskType.REFINEMENT,
                ),
                notes=("MoE plus second-stage refiner in the official release.",),
            ),
            ModelVariant(
                id="fastvideo-moe-30b-a3b",
                name="LingBot-Video MoE 30B-A3B FastVideo Port",
                hf_repo_id="FastVideo/LingBot-Video-MoE-30B-A3B-Diffusers",
                parameter_count="30B",
                active_parameter_count="3B",
                tasks=(TaskType.TEXT_TO_VIDEO,),
                resolutions=("480p", "1080p"),
                notes=("Community conversion useful for benchmarking an external serving runtime.",),
            ),
        ),
    ),
    ModelSpec(
        id="longcat-video",
        aliases=("longcat", "longcatvideo"),
        name="LongCat-Video",
        organization="Meituan LongCat",
        adapter="longcat-video",
        runtime=RuntimeKind.DIFFUSERS,
        status=SupportStatus.ADAPTER_SCAFFOLDED,
        default_variant="13.6b",
        license_id="mit",
        description="Long-video focused 13.6B model for T2V, I2V, and video continuation.",
        sources=(
            ModelSource("model", "https://huggingface.co/meituan-longcat/LongCat-Video"),
        ),
        variants=(
            ModelVariant(
                id="13.6b",
                name="LongCat-Video 13.6B",
                hf_repo_id="meituan-longcat/LongCat-Video",
                parameter_count="13.6B",
                tasks=(
                    TaskType.TEXT_TO_VIDEO,
                    TaskType.IMAGE_TO_VIDEO,
                    TaskType.VIDEO_CONTINUATION,
                ),
                resolutions=("720p",),
                fps=(30,),
                default_fps=30,
                notes=("Coarse-to-fine long video generation and block sparse attention upstream.",),
            ),
        ),
    ),
    ModelSpec(
        id="cosmos3",
        aliases=("cosmos", "nvidia-cosmos", "cosmos-3"),
        name="Cosmos 3",
        organization="NVIDIA",
        adapter="cosmos3",
        runtime=RuntimeKind.OMNI,
        status=SupportStatus.ADAPTER_SCAFFOLDED,
        default_variant="nano",
        license_id="openmdw-1.1",
        description="Omnimodal world model family for text, image, video, audio, and action generation.",
        sources=(
            ModelSource("code", "https://github.com/nvidia/cosmos"),
            ModelSource("model", "https://huggingface.co/nvidia/Cosmos3-Nano"),
            ModelSource("model", "https://huggingface.co/nvidia/Cosmos3-Super"),
        ),
        variants=(
            ModelVariant(
                id="nano",
                name="Cosmos3-Nano",
                hf_repo_id="nvidia/Cosmos3-Nano",
                parameter_count="16B",
                tasks=(
                    TaskType.TEXT_TO_IMAGE,
                    TaskType.TEXT_TO_VIDEO,
                    TaskType.IMAGE_TO_VIDEO,
                    TaskType.TEXT_TO_VIDEO_WITH_SOUND,
                    TaskType.ACTION_CONDITIONED,
                ),
                resolutions=("256p", "480p", "720p"),
                fps=(10, 16, 24, 30),
                default_resolution="480p",
                default_fps=24,
            ),
            ModelVariant(
                id="super",
                name="Cosmos3-Super",
                hf_repo_id="nvidia/Cosmos3-Super",
                parameter_count="64B",
                tasks=(
                    TaskType.TEXT_TO_IMAGE,
                    TaskType.TEXT_TO_VIDEO,
                    TaskType.IMAGE_TO_VIDEO,
                    TaskType.TEXT_TO_VIDEO_WITH_SOUND,
                    TaskType.ACTION_CONDITIONED,
                ),
                resolutions=("256p", "480p", "720p"),
                fps=(10, 16, 24, 30),
                default_resolution="480p",
                default_fps=24,
            ),
            ModelVariant(
                id="super-i2v",
                name="Cosmos3-Super-Image2Video",
                hf_repo_id="nvidia/Cosmos3-Super-Image2Video",
                parameter_count="64B",
                tasks=(TaskType.IMAGE_TO_VIDEO,),
                resolutions=("256p", "480p", "720p"),
                fps=(10, 16, 24, 30),
            ),
            ModelVariant(
                id="super-t2i",
                name="Cosmos3-Super-Text2Image",
                hf_repo_id="nvidia/Cosmos3-Super-Text2Image",
                parameter_count="64B",
                tasks=(TaskType.TEXT_TO_IMAGE,),
                resolutions=("256p", "480p", "720p"),
            ),
        ),
    ),
    ModelSpec(
        id="skyreels-v3",
        aliases=("skyreels", "skyreels3", "skyreels-v3"),
        name="SkyReels V3",
        organization="Skywork",
        adapter="skyreels-v3",
        runtime=RuntimeKind.DIFFUSERS,
        status=SupportStatus.ADAPTER_SCAFFOLDED,
        default_variant="r2v-14b",
        license_id="skywork-license",
        description="Multimodal in-context video family for reference-to-video, V2V, and talking avatar.",
        sources=(
            ModelSource("code", "https://github.com/SkyworkAI/SkyReels-V3"),
            ModelSource("collection", "https://huggingface.co/collections/Skywork/skyreels-v3"),
        ),
        variants=(
            ModelVariant(
                id="r2v-14b",
                name="SkyReels-V3 R2V 14B",
                hf_repo_id="Skywork/SkyReels-V3-R2V-14B",
                parameter_count="14B",
                tasks=(TaskType.REFERENCE_TO_VIDEO, TaskType.IMAGE_TO_VIDEO),
                resolutions=("720p",),
                fps=(24,),
                default_fps=24,
                notes=("Supports one to four reference images in upstream examples.",),
            ),
            ModelVariant(
                id="v2v-14b",
                name="SkyReels-V3 V2V 14B",
                hf_repo_id="Skywork/SkyReels-V3-V2V-14B",
                parameter_count="14B",
                tasks=(TaskType.VIDEO_TO_VIDEO, TaskType.VIDEO_CONTINUATION),
                resolutions=("720p",),
                notes=("Video extension supports 5 to 30 second single-shot continuations upstream.",),
            ),
            ModelVariant(
                id="a2v-19b",
                name="SkyReels-V3 A2V 19B",
                hf_repo_id="Skywork/SkyReels-V3-A2V-19B",
                parameter_count="19B",
                tasks=(TaskType.AUDIO_TO_VIDEO, TaskType.TALKING_AVATAR, TaskType.IMAGE_TO_VIDEO),
                resolutions=("720p",),
                fps=(24,),
                default_fps=24,
                notes=("Talking-avatar path consumes one image plus one audio file.",),
            ),
        ),
    ),
    ModelSpec(
        id="bernini",
        aliases=("bernini-r", "bytedance-bernini"),
        name="Bernini",
        organization="ByteDance",
        adapter="bernini",
        runtime=RuntimeKind.HYBRID,
        status=SupportStatus.ADAPTER_SCAFFOLDED,
        default_variant="renderer-wan22",
        description="Latent semantic planning framework with an MLLM planner and DiT renderer.",
        sources=(
            ModelSource("code", "https://github.com/bytedance/Bernini"),
            ModelSource("model", "https://huggingface.co/ByteDance/Bernini"),
            ModelSource("project", "https://bernini-ai.github.io/"),
        ),
        notes=("Current renderer release depends on Wan2.2 base components.",),
        variants=(
            ModelVariant(
                id="renderer-wan22",
                name="Bernini Renderer on Wan2.2",
                hf_repo_id="ByteDance/Bernini",
                tasks=(
                    TaskType.TEXT_TO_IMAGE,
                    TaskType.IMAGE_TO_IMAGE,
                    TaskType.TEXT_TO_VIDEO,
                    TaskType.IMAGE_TO_VIDEO,
                    TaskType.VIDEO_TO_VIDEO,
                    TaskType.VIDEO_EDITING,
                    TaskType.REFERENCE_TO_VIDEO,
                ),
                resolutions=("480p", "720p"),
                fps=(16, 24),
                notes=("Uses Wan2.2 base plus Bernini high-noise and low-noise checkpoints.",),
                extra={"base_model": "Wan-AI/Wan2.2-T2V-A14B-Diffusers"},
            ),
        ),
    ),
)
